config/routes.rb
Rails.application.routes.draw do
  resources :weathers
  resources :momentdays
  resources :batteries
  resources :materials 
  
  resources :games do
    
    member do
      get "stuff"
      get "battery"
      get "tick"
      get "circleobjects"
      get "word"
      get "materials"
      get "moment"
    end
  end
  resources :images
  resources :mysciences
  root "mysciences#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/battery.rb
class Battery < Stuff
  
end

app/models/circleobject.rb
class Circleobject < ApplicationRecord
  belongs_to :image
  belongs_to :game
end

app/models/crossortick.rb
class Crossortick < ApplicationRecord
  belongs_to :image
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :myscience
  has_many :circleobjects
  accepts_nested_attributes_for :circleobjects
  has_and_belongs_to_many :materials_images, :join_table => :gamehasmaterials
  #has_and_belongs_to_many :mystuffhaspics, :join_table => :mybatteries
  has_and_belongs_to_many :mystuffhaspics, :join_table => :gamehasstuffhaspics
  has_and_belongs_to_many :stuffs, :join_table => :gamehastuffs
  has_many :crossorticks
  accepts_nested_attributes_for :crossorticks
  has_many :images, :through => :crossorticks
  has_many :pics, through: :circleobjects, source: :image
  has_many :gamehaswords
  accepts_nested_attributes_for :gamehaswords, allow_destroy: true
      validate :validate_tags

  def validate_tags
    errors.add(:circleobjects, "not right nb must be equal 7") if pics.length > 0 and pics.length != 7
    errors.add(:materials, "add more objects") if materials_images.length > 0 and materials_images.length < 2
    errors.add(:word, "la description ne contient pas le mot") if gamehaswords.length > 0 and gamehaswords.any?{|h|!self.content.include?(h.text)}
    p "MY ERRORS/"
    p errors
  end
end

app/models/gamehasword.rb
class Gamehasword < ApplicationRecord
  belongs_to :game
end

app/models/image.rb
class Image < ApplicationRecord
  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/material.rb
class Material < Stuff
    has_and_belongs_to_many :images, :join_table => :materials_images


end

app/models/materials_image.rb
class MaterialsImage < ApplicationRecord
  belongs_to :material
  belongs_to :image
end

app/models/momentday.rb
class Momentday < Stuff
end

app/models/myscience.rb
class Myscience < ApplicationRecord
  has_many :games
end

app/models/mystuffhaspic.rb
class Mystuffhaspic < ApplicationRecord
  belongs_to :stuff
  belongs_to :image
  def self.batery
    all.joins(:stuff).select("*, mystuffhaspics.id as myid, stuffs.type as type").where("type = ?", "Battery")
  end
  def self.momentday
    all.joins(:stuff).select("mystuffhaspics.*, mystuffhaspics.id as myid, stuffs.type as type").where("type = ?", "Momentday")
  end
end

app/models/stuff.rb
class Stuff < ApplicationRecord
    has_and_belongs_to_many :pics, class_name:"Image", :join_table => :mystuffhaspics
    
    def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/weather.rb
class Weather < Stuff
end

app/controllers/mysciences_controller.rb
class MysciencesController < ApplicationController
  before_action :set_myscience, only: %i[ show edit update destroy ]

  # GET /mysciences or /mysciences.json
  def index
    @mysciences = Myscience.all
  end

  # GET /mysciences/1 or /mysciences/1.json
  def show
  end

  # GET /mysciences/new
  def new
    @myscience = Myscience.new
  end

  # GET /mysciences/1/edit
  def edit
  end

  # POST /mysciences or /mysciences.json
  def create
    @myscience = Myscience.new(myscience_params)

    respond_to do |format|
      if @myscience.save
        format.html { redirect_to myscience_url(@myscience), notice: "Myscience was successfully created." }
        format.json { render :show, status: :created, location: @myscience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @myscience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mysciences/1 or /mysciences/1.json
  def update
    respond_to do |format|
      if @myscience.update(myscience_params)
        format.html { redirect_to myscience_url(@myscience), notice: "Myscience was successfully updated." }
        format.json { render :show, status: :ok, location: @myscience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @myscience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mysciences/1 or /mysciences/1.json
  def destroy
    @myscience.destroy

    respond_to do |format|
      format.html { redirect_to mysciences_url, notice: "Myscience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myscience
      @myscience = Myscience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def myscience_params
      params.require(:myscience).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/momentdays_helper.rb
module MomentdaysHelper
end

app/helpers/mysciences_helper.rb
module MysciencesHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/mysciences/_form.html.erb
<%= form_with(model: myscience) do |form| %>
  <% if myscience.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(myscience.errors.count, "error") %> prohibited this myscience from being saved:</h2>

      <ul>
        <% myscience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mysciences/_myscience.html.erb
<div id="<%= dom_id myscience %>">
  <p>
    <strong>Title:</strong>
    <%= myscience.title %>
  </p>

</div>

app/views/mysciences/edit.html.erb
<h1>Editing myscience</h1>

<%= render "form", myscience: @myscience %>

<br>

<div>
  <%= link_to "Show this myscience", @myscience %> |
  <%= link_to "Back to mysciences", mysciences_path %>
</div>

app/views/mysciences/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mysciences</h1>

<div id="mysciences">
  <% @mysciences.each do |myscience| %>
    <%= render myscience %>
    <p>
      <%= link_to "Show this myscience", myscience %>
    </p>
  <% end %>
</div>

<%= link_to "New myscience", new_myscience_path %>

app/views/mysciences/new.html.erb
<h1>New myscience</h1>

<%= render "form", myscience: @myscience %>

<br>

<div>
  <%= link_to "Back to mysciences", mysciences_path %>
</div>

app/views/mysciences/show.html.erb
<p style="color: green"><%= notice %></p>

<h3><%=  @myscience.title %></h3>
<%if @myscience.games.length > 0%>
<%=render @myscience.games%>
<%else%>
<p>aucun jeux ajoutés pour cette science</p>
<%end%>
<div>
  <%= link_to "Edit this myscience", edit_myscience_path(@myscience) %> |
  <%= link_to "ajouter un jeu pour cette science", new_game_path(@myscience, myscience_id: @myscience.id) %> |
  <%= link_to "Back to mysciences", mysciences_path %>

  <%= button_to "Destroy this myscience", @myscience, method: :delete %>
</div>