config/routes.rb
Rails.application.routes.draw do
  resources :weathers
  resources :momentdays
  resources :batteries
  resources :materials 
  
  resources :games do
    
    member do
      get "stuff"
      get "battery"
      get "tick"
      get "circleobjects"
      get "word"
      get "materials"
      get "moment"
    end
  end
  resources :images
  resources :mysciences
  root "mysciences#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/battery.rb
class Battery < Stuff
  
end

app/models/circleobject.rb
class Circleobject < ApplicationRecord
  belongs_to :image
  belongs_to :game
end

app/models/crossortick.rb
class Crossortick < ApplicationRecord
  belongs_to :image
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :myscience
  has_many :circleobjects
  accepts_nested_attributes_for :circleobjects
  has_and_belongs_to_many :materials_images, :join_table => :gamehasmaterials
  #has_and_belongs_to_many :mystuffhaspics, :join_table => :mybatteries
  has_and_belongs_to_many :mystuffhaspics, :join_table => :gamehasstuffhaspics
  has_and_belongs_to_many :stuffs, :join_table => :gamehastuffs
  has_many :crossorticks
  accepts_nested_attributes_for :crossorticks
  has_many :images, :through => :crossorticks
  has_many :pics, through: :circleobjects, source: :image
  has_many :gamehaswords
  accepts_nested_attributes_for :gamehaswords, allow_destroy: true
      validate :validate_tags

  def validate_tags
    errors.add(:circleobjects, "not right nb must be equal 7") if pics.length > 0 and pics.length != 7
    errors.add(:materials, "add more objects") if materials_images.length > 0 and materials_images.length < 2
    errors.add(:word, "la description ne contient pas le mot") if gamehaswords.length > 0 and gamehaswords.any?{|h|!self.content.include?(h.text)}
    p "MY ERRORS/"
    p errors
  end
end

app/models/gamehasword.rb
class Gamehasword < ApplicationRecord
  belongs_to :game
end

app/models/image.rb
class Image < ApplicationRecord
  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/material.rb
class Material < Stuff
    has_and_belongs_to_many :images, :join_table => :materials_images


end

app/models/materials_image.rb
class MaterialsImage < ApplicationRecord
  belongs_to :material
  belongs_to :image
end

app/models/momentday.rb
class Momentday < Stuff
end

app/models/myscience.rb
class Myscience < ApplicationRecord
  has_many :games
end

app/models/mystuffhaspic.rb
class Mystuffhaspic < ApplicationRecord
  belongs_to :stuff
  belongs_to :image
  def self.batery
    all.joins(:stuff).select("*, mystuffhaspics.id as myid, stuffs.type as type").where("type = ?", "Battery")
  end
  def self.momentday
    all.joins(:stuff).select("mystuffhaspics.*, mystuffhaspics.id as myid, stuffs.type as type").where("type = ?", "Momentday")
  end
end

app/models/stuff.rb
class Stuff < ApplicationRecord
    has_and_belongs_to_many :pics, class_name:"Image", :join_table => :mystuffhaspics
    
    def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/weather.rb
class Weather < Stuff
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy circleobjects materials battery word moment tick stuff ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end
def word
  @game.gamehaswords.new
end
  # GET /games/new
  def new
    @game = Game.new(myscience_id: params[:myscience_id])
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        p @game.errors
        p @game.errors.messages
        format.html { render @game.errors.messages.to_a[0][0], status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end

  rescue => e
        p "ERREUR", e.message
        p @game.errors
    render :edit
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:myscience_id, :title, :content, :description,:crossorticks_attributes=>{},:gamehaswords_attributes=>{},:circleobjects_attributes=>{},:pic_ids=>[],:materials_image_ids=>[],:mystuffhaspic_ids=>[],:stuff_ids=>[],:image_ids=>[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/momentdays_helper.rb
module MomentdaysHelper
end

app/helpers/mysciences_helper.rb
module MysciencesHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :myscience_id, style: "display: block" %>
    <%= form.select :myscience_id, Myscience.all.collect{|h|[h.title, h.id]} %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_formbattery.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%if Mystuffhaspic.batery.length > 0%>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%=form.collection_check_boxes(:mystuffhaspic_ids, Mystuffhaspic.batery, :id, :image_id) do |b|%>
      <%=b.label(class: "check_box") do%>
      <%=b.check_box(class: "check_box")%>
      <%=render b.object%>
    <%end%>
    <%end%>
  </div>
<%else%>
<p>ajouter des batteries et des objets avec cette batterie</p>
<%end%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_formcircle.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%if Image.all.length > 0%>

  <%if game.pics.length == 0%>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%=form.collection_check_boxes(:pic_ids, Image.all, :id, :title) do |b|%>
      <%=b.label(class: "check_box") do%>
      <%=b.check_box(class: "check_box")%>
      <img src="/uploads/<%=b.object.image%>" style="width:100px;height:100px;"/>
    <%end%>
    <%end%>
  </div>
<%else%>
  <p>should the users <%=game.description%> ?</p>
  <%=form.fields_for :circleobjects do |f|%>
    <div>
      <img src="/uploads/<%=f.object.image.image%>" style="width:100px;height:100px;"/>
        <table>
        <tr>
            <td><%= f.label 'a_flag_true', 'Oui' %></td>
            <td><%= f.radio_button :mycond, true %></td>
        </tr>

        <tr>
            <td><%= f.label 'a_flag_false', 'Non' %></td>
            <td><%= f.radio_button :mycond, false %></td>
        </tr>
    </table>
    </div>
<%end%>
<%end%>
<%else%>
  <p>ajouter des image</p>
  <%end%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_formmaterials.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%if MaterialsImage.all.length > 0%>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%=form.collection_check_boxes(:materials_image_ids, MaterialsImage.all, :id, :image_id) do |b|%>
      <%=b.label(class: "check_box") do%>
      <%=b.check_box(class: "check_box")%>
      <%=render b.object%>
    <%end%>
    <%end%>
  </div>
<%else%>
<p>ajouter des images et des matériaux que cette image a </p>
<%end%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_formstuff.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%if Stuff.all.length > 0%>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%=form.collection_check_boxes(:stuff_ids, Stuff.all, :id, :id) do |b|%>
      <%=b.label(class: "check_box") do%>
      <%=b.check_box(class: "check_box")%>
      <%=render b.object%>
    <%end%>
    <%end%>
  </div>
<%else%>
<p>ajouter des choses, materiaux, temps , moment de la journée</p>
<%end%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_formword.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%=form.fields_for :gamehaswords do |f|%>
<div>
    <label>mot à deviner</label>
    <%=f.text_field :text%>
</div>
<%end%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/circleobjects.html.erb
<h1>Editing game</h1>

<%= render "formcircle", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path %>

app/views/games/materials.html.erb
<h1>Editing game</h1>

<%= render "formmaterials", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/moment.html.erb
<h1>Editing game</h1>

<%= render "formmoment", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="msg"></div>
<%= render @game %>
<%= render @game.circleobjects %>
<%= render @game.crossorticks %>
<%if @game.crossorticks.length > 0%>
<p>tick or cross the box under the pic</p>
<%end%>
<%if @game.materials_images.length > 0 %>
<%@x=@game.materials_images.shuffle%>
<%@k=@game.materials_images.shuffle%>
    <table>
        <%@x.each_with_index do |h,i|%>
            <tr>
                    <td>
                        
                  <input type="radio" name="a" onchange="msg.innerHTML=(document.querySelector('[name=a]:checked').value === document.querySelector('[name=b]:checked').value ? ('OK') : '');" value="<%=h.id%>" />
                  <%=render h.image%>
                </td>
                <td>
                    <input type="radio" name="b" onchange="msg.innerHTML=(document.querySelector('[name=a]:checked').value === document.querySelector('[name=b]:checked').value ? ('OK') : '');" value="<%=@k[i].id%>" />
                    <%=@k[i].material.name%>
                </td>
        </tr>
        <%end%>
</table>
<%end%>
<%if @game.stuffs.length > 0 %>
<%@x=@game.stuffs.shuffle%>
<%@k=@game.stuffs.shuffle%>
    <table>
        <%@x.each_with_index do |h,i|%>
            <tr>
                    <td>
                        
                  <input type="radio" name="a" onchange="$('[name=a], [name=b]').parent().attr('style','border:0px solid black;');$('[name=a]:checked, [name=b]:checked').parent().attr('style','border:'+(document.querySelector('[name=a]:checked').value === document.querySelector('[name=b]:checked').value ? ('1px solid green;') : '1px solid red;'));" onfocusout="this.parentElement.style.border='0px solid';" onblur="this.parentElement.style.border='0px solid';" value="<%=h.id%>" />
                  <img src="/uploads/<%= h.image%>" />
                 
                </td>
                <td>
                    <input type="radio" name="b" onchange="$('[name=a], [name=b]').parent().attr('style','border:0px solid black;');$('[name=a]:checked, [name=b]:checked').parent().attr('style','border:'+(document.querySelector('[name=a]:checked').value === document.querySelector('[name=b]:checked').value ? ('1px solid green;') : '1px solid red;'));" onfocusout="this.parentElement.style.border='0px';" onblur="this.parentElement.style.border='0px solid';" value="<%=@k[i].id%>" />
                  
                    <%=@k[i].name%>
                </td>
        </tr>
        <%end%>
</table>
<%end%>
<%if @game.mystuffhaspics.batery.length > 0 %>
<%@x=@game.mystuffhaspics.batery.shuffle%>
<%@k=@game.mystuffhaspics.batery.shuffle%>
    <table>
        <%@x.each_with_index do |h,i|%>
            <tr>
                    <td>
                        
                  <input type="radio" name="a" onchange="msg.innerHTML=(document.querySelector('[name=a]:checked').value === document.querySelector('[name=b]:checked').value ? ('OK') : '');" value="<%=h.id%>" />
                  <img src="/uploads/<%= h.image.image%>" />
                  <%= h.image.title%>
                </td>
                <td>
                    <input type="radio" name="b" onchange="msg.innerHTML=(document.querySelector('[name=a]:checked').value === document.querySelector('[name=b]:checked').value ? ('OK') : '');" value="<%=@k[i].id%>" />
                    <img src="/uploads/<%=@k[i].stuff.image%>" />
                    <%=@k[i].stuff.name%>
                </td>
        </tr>
        <%end%>
</table>
<%end%>
<%@game.gamehaswords.each do |xx|%>
<%[@game.content.split(".").select{|h|h.include?(xx.text)}.sample].each do |x|%>
<p>
<%x.split(xx.text).each_with_index do |a,i|%>
<%if i==1%>
<input type="text" name="azertyu" onkeyup="this.style.border = this.value === '<%=xx.text.strip.squish%>' ? '5px solid green' : '1px solid red'"/> (<%=xx.text.split("").shuffle.join%>)
<%end%>
<%=a%>

<%end%>.
</p>
  <%end%>

<%end%>

<%if @game.mystuffhaspics.momentday.length > 0%>
<p>
écris dans les cases
<%=@game.mystuffhaspics.momentday.uniq{|j|j.stuff_id}.map{|g|"#{g.stuff.name[0..2]} pour #{g.stuff.name}"}.to_sentence%>
  </p>
<%@game.mystuffhaspics.momentday.to_a.uniq{|j|j.stuff_id}.each do |h|%>

    <div>
      <%=h.image.title%>
      <img src="/uploads/<%=h.image.image%>" id="img<%=h.id%>"/>
      <input type="text" onkeyup="img<%=h.id%>.style.border = (this.value === '<%=h.stuff.name[0..2]%>' ? '5px solid green' : '5px solid red');"/>
  
</div>
<%end%>
<%end%>
<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "jouer à ce jeu comme pour entourer les objets", circleobjects_game_path(@game) %> |
  <%= link_to "jouer à trouver des matériaux d'objets", materials_game_path(@game) %> |
  <%= link_to "jouer à trouver les batteries des objets", battery_game_path(@game) %> |
  <%= link_to "ajouter un mot à faire deviner", word_game_path(@game) %> |
  <%= link_to "ajouter un moment de la journée à faire deviner", moment_game_path(@game) %> |
  <%= link_to "ajouter des choses à associer l'image et le mot", stuff_game_path(@game) %> |
  <%= link_to "dire si une action est bonne ou mauvaise", tick_game_path(@game) %> |
  <%= link_to "Back to games", games_path %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/games/stuff.html.erb
<h1>Editing game</h1>

<%= render "formstuff", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/tick.html.erb
<h1>Editing game</h1>

<%= render "formtick", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>