config/routes.rb
Rails.application.routes.draw do
  resources :weathers
  resources :momentdays
  resources :batteries
  resources :materials 
  
  resources :games do
    
    member do
      get "stuff"
      get "battery"
      get "tick"
      get "circleobjects"
      get "word"
      get "materials"
      get "moment"
    end
  end
  resources :images
  resources :mysciences
  root "mysciences#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/battery.rb
class Battery < Stuff
  
end

app/models/circleobject.rb
class Circleobject < ApplicationRecord
  belongs_to :image
  belongs_to :game
end

app/models/crossortick.rb
class Crossortick < ApplicationRecord
  belongs_to :image
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :myscience
  has_many :circleobjects
  accepts_nested_attributes_for :circleobjects
  has_and_belongs_to_many :materials_images, :join_table => :gamehasmaterials
  #has_and_belongs_to_many :mystuffhaspics, :join_table => :mybatteries
  has_and_belongs_to_many :mystuffhaspics, :join_table => :gamehasstuffhaspics
  has_and_belongs_to_many :stuffs, :join_table => :gamehastuffs
  has_many :crossorticks
  accepts_nested_attributes_for :crossorticks
  has_many :images, :through => :crossorticks
  has_many :pics, through: :circleobjects, source: :image
  has_many :gamehaswords
  accepts_nested_attributes_for :gamehaswords, allow_destroy: true
      validate :validate_tags

  def validate_tags
    errors.add(:circleobjects, "not right nb must be equal 7") if pics.length > 0 and pics.length != 7
    errors.add(:materials, "add more objects") if materials_images.length > 0 and materials_images.length < 2
    errors.add(:word, "la description ne contient pas le mot") if gamehaswords.length > 0 and gamehaswords.any?{|h|!self.content.include?(h.text)}
    p "MY ERRORS/"
    p errors
  end
end

app/models/gamehasword.rb
class Gamehasword < ApplicationRecord
  belongs_to :game
end

app/models/image.rb
class Image < ApplicationRecord
  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/material.rb
class Material < Stuff
    has_and_belongs_to_many :images, :join_table => :materials_images


end

app/models/materials_image.rb
class MaterialsImage < ApplicationRecord
  belongs_to :material
  belongs_to :image
end

app/models/momentday.rb
class Momentday < Stuff
end

app/models/myscience.rb
class Myscience < ApplicationRecord
  has_many :games
end

app/models/mystuffhaspic.rb
class Mystuffhaspic < ApplicationRecord
  belongs_to :stuff
  belongs_to :image
  def self.batery
    all.joins(:stuff).select("*, mystuffhaspics.id as myid, stuffs.type as type").where("type = ?", "Battery")
  end
  def self.momentday
    all.joins(:stuff).select("mystuffhaspics.*, mystuffhaspics.id as myid, stuffs.type as type").where("type = ?", "Momentday")
  end
end

app/models/stuff.rb
class Stuff < ApplicationRecord
    has_and_belongs_to_many :pics, class_name:"Image", :join_table => :mystuffhaspics
    
    def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/weather.rb
class Weather < Stuff
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/momentdays_helper.rb
module MomentdaysHelper
end

app/helpers/mysciences_helper.rb
module MysciencesHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Science</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%=link_to "bienvenue", root_path%>
      <%=link_to "voir toutes les images", images_path%>
      <%=link_to "voir toutes les games", games_path%>
      <%=link_to "voir tous les matériaux", materials_path%>
      <%=link_to "voir toutes les sciences", mysciences_path%>
      <%=link_to "voir toutes les piles", batteries_path%>
      <%=link_to "voir toutes les moments de la journée", momentdays_path%>
      <%=link_to "voir toutesles temps qu'il fait", weathers_path%>
    </nav>
    <%= yield %>
     <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
     <%= yield :js %>
  </body>
</html>